version: "3.3"

networks:
    websocket-network:

services:
    mongodb_chat:
        container_name: mongodb_chat
        image: mongo
        networks: 
            - websocket-network

    chat-server:
        container_name: chat-server
        image: chat-server:1.0
        build: ./server
        networks: 
            - websocket-network
        depends_on: 
            - mongodb_chat
    
    chat-client:
        container_name: chat-client
        image: chat-client:1.0
        build: ./client
        ports: 
            - 8088:8088
        networks: 
            - websocket-network
        depends_on: 
            - chat-server
        environment: 
            - PORT=8088
    
    chat-client-2:
        container_name: chat-client-2
        image: chat-client:1.0
        build: ./client
        ports: 
            - 8081:8081
        networks: 
            - websocket-network
        depends_on: 
            - chat-server
        environment: 
            - PORT=8081
    
    chat-client-3:
        container_name: chat-client-3
        image: chat-client:1.0
        build: ./client
        ports: 
            - 8082:8082
        networks: 
            - websocket-network
        depends_on: 
            - chat-server
        environment: 
            - PORT=8082